rapidflask:
  restart: always
  build: ./dojo
  expose:
    - "52323"
  links:
    - redis
    - postgres
  volumes:
    - ./rapidflask:/srv/rapidflask
  env_file: .env
  working_dir: /srv/rapidflask/
  command: /usr/src/rapidflask/rAPPenv/bin/gunicorn -w 2 -b :52323 manage:app


nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - rapidflask
  links:
    - rapidflask:rapidflask

data:
  restart: "no"
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    LC_ALL: C.UTF-8
  volumes_from:
    - data
  ports:
    - "5432:5432"


redis:
  image: redis:2.8.21
  ports:
    - 6379:6379
  volumes:
    - ~/.docker-volumes/rapidflask/redis/data:/var/lib/redis/data
  environment:
    LC_ALL: C.UTF-8
